name: Deploy FastAPI to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GKE_REGION }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
  IMAGE_NAME: mlops-fastapi
  ARTIFACT_REPO: mlops-test
  IMAGE_TAG: latest

# -------------------------
# JOB 1: BUILD DOCKER IMAGE
# -------------------------
jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build \
          -t $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/$IMAGE_NAME:$IMAGE_TAG \
          .

# -------------------------
# JOB 2: PUSH IMAGE
# -------------------------
  push-image:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

    - name: Push Docker image
      run: |
        docker push \
          $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/$IMAGE_NAME:$IMAGE_TAG

# -------------------------
# JOB 3: DEPLOY TO GKE
# -------------------------
  deploy-gke:
    runs-on: ubuntu-latest
    needs: push-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    # âœ… Correct way to install plugin
    - name: Install GKE auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER_NAME \
          --region $GCP_REGION \
          --project $PROJECT_ID

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s-deploy.yml
